[build-dependencies]
vergen = '3.0.4'

[build-dependencies.build-script-utils]
package = 'substrate-build-script-utils'
version = '2.0.0-alpha.3'

[package]
name = "pki-node"
build = "build.rs"
version = "2.0.0"
authors = ['Eliott Teissonniere <git.eliott@teissonniere.org>']
edition = "2018"
repository = "https://github.com/NodleCode/pki"

[[bin]]
name = 'pki-node'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
structopt = '0.3.8'

[dependencies.grandpa]
package = 'sc-finality-grandpa'
version = '0.8.0-alpha.3'

[dependencies.grandpa-primitives]
package = 'sp-finality-grandpa'
version = '2.0.0-alpha.3'

[dependencies.pki-runtime]
path = '../runtime'
version = '2.0.0-alpha.3'

[dependencies.sc-basic-authorship]
version = '0.8.0-alpha.3'

[dependencies.sc-cli]
version = '0.8.0-alpha.3'

[dependencies.sc-client]
version = '0.8.0-alpha.3'

[dependencies.sc-client-api]
version = '2.0.0-alpha.3'

[dependencies.sc-consensus-aura]
version = '0.8.0-alpha.3'

[dependencies.sc-executor]
version = '0.8.0-alpha.3'

[dependencies.sc-network]
version = '0.8.0-alpha.3'

[dependencies.sc-service]
version = '0.8.0-alpha.3'

[dependencies.sc-transaction-pool]
version = '2.0.0-alpha.3'

[dependencies.sp-consensus]
version = '0.8.0-alpha.3'

[dependencies.sp-consensus-aura]
version = '0.8.0-alpha.3'

[dependencies.sp-core]
version = '2.0.0-alpha.3'

[dependencies.sp-inherents]
version = '2.0.0-alpha.3'

[dependencies.sp-runtime]
version = '2.0.0-alpha.3'

[dependencies.sp-transaction-pool]
version = '2.0.0-alpha.3'
